### ISSUE TITLE
关于flow使用，是否要添加.flowOn(Dispatchers.IO)切换子线程，否则就是在主线程请求了

### ISSUE THREAD

**Issue by jackyHuangH** [huanglinqing123/TravelPrevention#2]
/**
     * 查询 风险等级数据
     */
    fun loadRiskLevelMessage() = flow {
        val data = RiskLevelRespository().loadRiskLevelMessage()
         //打印当前线程
        Log.d("Risk", "thread:${Thread.currentThread().name}")
        
        emit(data)
    }.flowOn(Dispatchers.IO)//上游请求切换子线程
        .catch {
        if (it is Exception) {
            HttpErrorDeal.dealHttpError(it)
        }
        emit(null)
    }.asLiveData()

**Comment by huanglinqing123** [comment]
不需要的，因为这里使用的retrofit api中加了suspend关键字，retrofit会自动切换到IO线程，用flow再切一次是没有意义的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月14日(周五) 下午4:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [huanglinqing123/TravelPrevention] 关于flow使用，是否要添加.flowOn(Dispatchers.IO)切换子线程，否则就是在主线程请求了 (Issue #2)




 
/**
 * 查询 风险等级数据
 */
 fun loadRiskLevelMessage() = flow {
 val data = RiskLevelRespository().loadRiskLevelMessage()
 //打印当前线程
 Log.d("Risk", "thread:${Thread.currentThread().name}")
     emit(data) }.flowOn(Dispatchers.IO)//上游请求切换子线程     .catch {     if (it is Exception) {         HttpErrorDeal.dealHttpError(it)     }     emit(null) }.asLiveData()

**Comment by jackyHuangH** [comment]
OK，了解了
